"""add user_location

Revision ID: 5ac701db4ca4
Revises: f4985022353a
Create Date: 2019-05-21 10:59:29.854061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ac701db4ca4'
down_revision = 'f4985022353a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location', sa.String(length=64), nullable=True))
    op.drop_column('users', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('localtion', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('users', 'location')
    # ### end Alembic commands ###
